
---
- name: Linode VPN Playbook
  hosts: all
  become: yes

  tasks:
    - name: Install all available updates
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install packages
      apt:
        pkg:
        - neovim
        - git
        - wget
        - net-tools
        - curl
        state: latest

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
    
    - name: Execute the script to setup vpn server
      environment:
        CLIENT: "{{ client_name }}"
      command: bash /root/setup.sh
 
